/*
 * This file was automatically generated by EvoSuite
 * Thu May 02 07:11:48 GMT 2024
 */

package statechart;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import statechart.EntryExitSimplified;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EntryExitSimplified_ESTest extends EntryExitSimplified_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      entryExitSimplified0.exit();
      assertFalse(entryExitSimplified0.isFinal());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      entryExitSimplified0.raiseC();
      entryExitSimplified0.runCycle();
      entryExitSimplified0.enter();
      assertTrue(entryExitSimplified0.isActive());
      
      entryExitSimplified0.exit();
      assertFalse(entryExitSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      entryExitSimplified0.raiseB();
      entryExitSimplified0.runCycle();
      entryExitSimplified0.enter();
      assertTrue(entryExitSimplified0.isActive());
      
      entryExitSimplified0.exit();
      assertFalse(entryExitSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      entryExitSimplified0.enter();
      assertTrue(entryExitSimplified0.isActive());
      
      entryExitSimplified0.exit();
      assertFalse(entryExitSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      entryExitSimplified0.raiseA();
      entryExitSimplified0.enter();
      entryExitSimplified0.raiseNext();
      entryExitSimplified0.runCycle();
      EntryExitSimplified.State entryExitSimplified_State0 = EntryExitSimplified.State.MAIN_REGION__FINAL_;
      boolean boolean0 = entryExitSimplified0.isStateActive(entryExitSimplified_State0);
      assertTrue(entryExitSimplified0.isActive());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      entryExitSimplified0.raiseB();
      entryExitSimplified0.enter();
      entryExitSimplified0.runCycle();
      EntryExitSimplified.State entryExitSimplified_State0 = EntryExitSimplified.State.MAIN_REGION_MULTIPLE_ALTERNATIVES;
      boolean boolean0 = entryExitSimplified0.isStateActive(entryExitSimplified_State0);
      assertTrue(entryExitSimplified0.isActive());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      EntryExitSimplified.State entryExitSimplified_State0 = EntryExitSimplified.State.MAIN_REGION_MULTIPLE_ALTERNATIVES;
      entryExitSimplified0.enter();
      boolean boolean0 = entryExitSimplified0.isStateActive(entryExitSimplified_State0);
      assertTrue(entryExitSimplified0.isActive());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      entryExitSimplified0.enter();
      EntryExitSimplified.State entryExitSimplified_State0 = EntryExitSimplified.State.MAIN_REGION_INIT;
      boolean boolean0 = entryExitSimplified0.isStateActive(entryExitSimplified_State0);
      assertTrue(entryExitSimplified0.isActive());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      EntryExitSimplified.State entryExitSimplified_State0 = EntryExitSimplified.State.$NULLSTATE$;
      boolean boolean0 = entryExitSimplified0.isStateActive(entryExitSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      assertFalse(entryExitSimplified0.isActive());
      
      EntryExitSimplified.State entryExitSimplified_State0 = EntryExitSimplified.State.MAIN_REGION_MULTIPLE_ALTERNATIVES;
      boolean boolean0 = entryExitSimplified0.isStateActive(entryExitSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      EntryExitSimplified.State entryExitSimplified_State0 = EntryExitSimplified.State.MAIN_REGION_D;
      entryExitSimplified0.isStateActive(entryExitSimplified_State0);
      assertFalse(entryExitSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      EntryExitSimplified.State entryExitSimplified_State0 = EntryExitSimplified.State.MAIN_REGION__FINAL_;
      boolean boolean0 = entryExitSimplified0.isStateActive(entryExitSimplified_State0);
      assertFalse(boolean0);
      assertFalse(entryExitSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      EntryExitSimplified.State entryExitSimplified_State0 = EntryExitSimplified.State.MAIN_REGION_MULTIPLE_ALTERNATIVES_R1_C;
      boolean boolean0 = entryExitSimplified0.isStateActive(entryExitSimplified_State0);
      assertFalse(entryExitSimplified0.isActive());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      EntryExitSimplified.State entryExitSimplified_State0 = EntryExitSimplified.State.MAIN_REGION_MULTIPLE_ALTERNATIVES_R1_B;
      boolean boolean0 = entryExitSimplified0.isStateActive(entryExitSimplified_State0);
      assertFalse(entryExitSimplified0.isActive());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      EntryExitSimplified.State entryExitSimplified_State0 = EntryExitSimplified.State.MAIN_REGION_MULTIPLE_ALTERNATIVES_R1_A;
      boolean boolean0 = entryExitSimplified0.isStateActive(entryExitSimplified_State0);
      assertFalse(boolean0);
      assertFalse(entryExitSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      EntryExitSimplified.State entryExitSimplified_State0 = EntryExitSimplified.State.MAIN_REGION_E;
      boolean boolean0 = entryExitSimplified0.isStateActive(entryExitSimplified_State0);
      assertFalse(entryExitSimplified0.isActive());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      EntryExitSimplified.State entryExitSimplified_State0 = EntryExitSimplified.State.MAIN_REGION_INIT;
      boolean boolean0 = entryExitSimplified0.isStateActive(entryExitSimplified_State0);
      assertFalse(boolean0);
      assertFalse(entryExitSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      boolean boolean0 = entryExitSimplified0.isFinal();
      assertFalse(boolean0);
      assertFalse(entryExitSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      assertFalse(entryExitSimplified0.isActive());
      
      entryExitSimplified0.enter();
      boolean boolean0 = entryExitSimplified0.isActive();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      boolean boolean0 = entryExitSimplified0.isActive();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      entryExitSimplified0.raiseA();
      entryExitSimplified0.enter();
      entryExitSimplified0.raiseNext();
      entryExitSimplified0.runCycle();
      assertTrue(entryExitSimplified0.isActive());
      
      entryExitSimplified0.exit();
      assertFalse(entryExitSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      entryExitSimplified0.raiseA();
      entryExitSimplified0.raiseNext();
      entryExitSimplified0.enter();
      entryExitSimplified0.runCycle();
      boolean boolean0 = entryExitSimplified0.isFinal();
      assertTrue(entryExitSimplified0.isActive());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      entryExitSimplified0.raiseB();
      entryExitSimplified0.raiseNext();
      entryExitSimplified0.runCycle();
      entryExitSimplified0.enter();
      assertTrue(entryExitSimplified0.isFinal());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      entryExitSimplified0.raiseA();
      entryExitSimplified0.enter();
      entryExitSimplified0.runCycle();
      assertTrue(entryExitSimplified0.isActive());
      
      entryExitSimplified0.exit();
      assertFalse(entryExitSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      EntryExitSimplified entryExitSimplified0 = new EntryExitSimplified();
      entryExitSimplified0.raiseC();
      entryExitSimplified0.enter();
      entryExitSimplified0.raiseNext();
      entryExitSimplified0.runCycle();
      assertTrue(entryExitSimplified0.isFinal());
  }
}
