/*
 * This file was automatically generated by EvoSuite
 * Tue May 21 06:24:02 GMT 2024
 */

package statechart;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.yakindu.core.ITimerService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import statechart.Network_ComponentSimplified;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Network_ComponentSimplified_ESTest extends Network_ComponentSimplified_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      // Undeclared exception!
      try { 
        network_ComponentSimplified0.raiseTimeEvent(1047);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1047
         //
         verifyException("statechart.Network_ComponentSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      // Undeclared exception!
      try { 
        network_ComponentSimplified0.raiseOff();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Timer service must be set.
         //
         verifyException("statechart.Network_ComponentSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      // Undeclared exception!
      try { 
        network_ComponentSimplified0.isStateActive((Network_ComponentSimplified.State) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("statechart.Network_ComponentSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      network_ComponentSimplified0.enter();
      network_ComponentSimplified0.setTimerService((ITimerService) null);
      // Undeclared exception!
      try { 
        network_ComponentSimplified0.exit();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("statechart.Network_ComponentSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      network_ComponentSimplified0.enter();
      network_ComponentSimplified0.raiseOff();
      network_ComponentSimplified0.triggerWithoutEvent();
      assertTrue(network_ComponentSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      network_ComponentSimplified0.enter();
      network_ComponentSimplified0.raiseTimeEvent(0);
      assertTrue(network_ComponentSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      network_ComponentSimplified0.enter();
      network_ComponentSimplified0.raiseOn();
      assertTrue(network_ComponentSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      network_ComponentSimplified0.enter();
      network_ComponentSimplified0.raiseOff();
      assertTrue(network_ComponentSimplified0.isActive());
      
      network_ComponentSimplified0.exit();
      assertFalse(network_ComponentSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      network_ComponentSimplified0.enter();
      assertTrue(network_ComponentSimplified0.isActive());
      
      network_ComponentSimplified0.exit();
      assertFalse(network_ComponentSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      network_ComponentSimplified0.enter();
      network_ComponentSimplified0.raiseOff();
      Network_ComponentSimplified.State network_ComponentSimplified_State0 = Network_ComponentSimplified.State._NETWORK_COMPONENT___OFF_;
      boolean boolean0 = network_ComponentSimplified0.isStateActive(network_ComponentSimplified_State0);
      assertTrue(network_ComponentSimplified0.isActive());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      network_ComponentSimplified0.enter();
      Network_ComponentSimplified.State network_ComponentSimplified_State0 = Network_ComponentSimplified.State._NETWORK_COMPONENT___NETWORK_COMPONENT_WORKING___NETWORK_CONNECTION__CHECKINGFORNETWORKCONNECTION__CHECKINGFORCONNECTIONUPDATES__CONNECTINGTOSERVER__SERVER_CONNECTION__SUCCESS;
      boolean boolean0 = network_ComponentSimplified0.isStateActive(network_ComponentSimplified_State0);
      assertTrue(network_ComponentSimplified0.isActive());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      Network_ComponentSimplified.State network_ComponentSimplified_State0 = Network_ComponentSimplified.State._NETWORK_COMPONENT___NETWORK_COMPONENT_WORKING___NETWORK_CONNECTION__CHECKINGFORNETWORKCONNECTION__CHECKINGFORCONNECTIONUPDATES__CONNECTINGTOSERVER;
      network_ComponentSimplified0.enter();
      boolean boolean0 = network_ComponentSimplified0.isStateActive(network_ComponentSimplified_State0);
      assertTrue(network_ComponentSimplified0.isActive());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      network_ComponentSimplified0.enter();
      Network_ComponentSimplified.State network_ComponentSimplified_State0 = Network_ComponentSimplified.State._NETWORK_COMPONENT___NETWORK_COMPONENT_WORKING___NETWORK_CONNECTION__CHECKINGFORNETWORKCONNECTION;
      boolean boolean0 = network_ComponentSimplified0.isStateActive(network_ComponentSimplified_State0);
      assertTrue(network_ComponentSimplified0.isActive());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      network_ComponentSimplified0.enter();
      Network_ComponentSimplified.State network_ComponentSimplified_State0 = Network_ComponentSimplified.State._NETWORK_COMPONENT___NETWORK_COMPONENT_WORKING_;
      boolean boolean0 = network_ComponentSimplified0.isStateActive(network_ComponentSimplified_State0);
      assertTrue(network_ComponentSimplified0.isActive());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      Network_ComponentSimplified.State network_ComponentSimplified_State0 = Network_ComponentSimplified.State.$NULLSTATE$;
      boolean boolean0 = network_ComponentSimplified0.isStateActive(network_ComponentSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      Network_ComponentSimplified.State network_ComponentSimplified_State0 = Network_ComponentSimplified.State._NETWORK_COMPONENT___NETWORK_COMPONENT_WORKING___NETWORK_CONNECTION__CHECKINGFORNETWORKCONNECTION__CHECKINGFORCONNECTIONUPDATES__CONNECTINGTOSERVER;
      boolean boolean0 = network_ComponentSimplified0.isStateActive(network_ComponentSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      Network_ComponentSimplified.State network_ComponentSimplified_State0 = Network_ComponentSimplified.State._NETWORK_COMPONENT___NETWORK_COMPONENT_WORKING___NETWORK_CONNECTION__CHECKINGFORNETWORKCONNECTION;
      boolean boolean0 = network_ComponentSimplified0.isStateActive(network_ComponentSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      Network_ComponentSimplified.State network_ComponentSimplified_State0 = Network_ComponentSimplified.State._NETWORK_COMPONENT___OFF_;
      boolean boolean0 = network_ComponentSimplified0.isStateActive(network_ComponentSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Network_ComponentSimplified.State network_ComponentSimplified_State0 = Network_ComponentSimplified.State._NETWORK_COMPONENT___NETWORK_COMPONENT_WORKING___NETWORK_CONNECTION__NETWORKTIMEOUT;
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      boolean boolean0 = network_ComponentSimplified0.isStateActive(network_ComponentSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      Network_ComponentSimplified.State network_ComponentSimplified_State0 = Network_ComponentSimplified.State._NETWORK_COMPONENT___NETWORK_COMPONENT_WORKING___NETWORK_CONNECTION__CHECKINGFORNETWORKCONNECTION__CHECKINGFORCONNECTIONUPDATES__CONNECTINGTOSERVER__SERVER_CONNECTION__FAILURE;
      boolean boolean0 = network_ComponentSimplified0.isStateActive(network_ComponentSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      Network_ComponentSimplified.State network_ComponentSimplified_State0 = Network_ComponentSimplified.State._NETWORK_COMPONENT___NETWORK_COMPONENT_WORKING_;
      boolean boolean0 = network_ComponentSimplified0.isStateActive(network_ComponentSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      Network_ComponentSimplified.State network_ComponentSimplified_State0 = Network_ComponentSimplified.State._NETWORK_COMPONENT___NETWORK_COMPONENT_WORKING___NETWORK_CONNECTION__CHECKINGFORNETWORKCONNECTION__CHECKINGFORCONNECTIONUPDATES__CONNECTINGTOSERVER__SERVER_CONNECTION__SUCCESS;
      boolean boolean0 = network_ComponentSimplified0.isStateActive(network_ComponentSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      network_ComponentSimplified0.raiseOff();
      assertFalse(network_ComponentSimplified0.isFinal());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      network_ComponentSimplified0.enter();
      boolean boolean0 = network_ComponentSimplified0.isActive();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      boolean boolean0 = network_ComponentSimplified0.isActive();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      // Undeclared exception!
      try { 
        network_ComponentSimplified0.enter();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Timer service must be set.
         //
         verifyException("statechart.Network_ComponentSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      // Undeclared exception!
      try { 
        network_ComponentSimplified0.raiseTimeEvent(1);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Timer service must be set.
         //
         verifyException("statechart.Network_ComponentSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      // Undeclared exception!
      try { 
        network_ComponentSimplified0.raiseOn();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Timer service must be set.
         //
         verifyException("statechart.Network_ComponentSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      // Undeclared exception!
      try { 
        network_ComponentSimplified0.triggerWithoutEvent();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Timer service must be set.
         //
         verifyException("statechart.Network_ComponentSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      boolean boolean0 = network_ComponentSimplified0.isFinal();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      network_ComponentSimplified0.setTimerService(iTimerService0);
      network_ComponentSimplified0.enter();
      network_ComponentSimplified0.raiseOff();
      network_ComponentSimplified0.raiseOn();
      assertFalse(network_ComponentSimplified0.isFinal());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Network_ComponentSimplified network_ComponentSimplified0 = new Network_ComponentSimplified();
      network_ComponentSimplified0.exit();
      assertFalse(network_ComponentSimplified0.isActive());
  }
}
