/*
 * This file was automatically generated by EvoSuite
 * Tue May 21 07:46:34 GMT 2024
 */

package statechart;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.yakindu.core.ITimerService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import statechart.SampleSimplified;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SampleSimplified_ESTest extends SampleSimplified_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      // Undeclared exception!
      try { 
        sampleSimplified0.raiseToggle_brightness();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Timer service must be set.
         //
         verifyException("statechart.SampleSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      // Undeclared exception!
      try { 
        sampleSimplified0.raiseToggle();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Timer service must be set.
         //
         verifyException("statechart.SampleSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      // Undeclared exception!
      try { 
        sampleSimplified0.raiseTimeEvent(3);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Timer service must be set.
         //
         verifyException("statechart.SampleSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      // Undeclared exception!
      try { 
        sampleSimplified0.raiseTimeEvent((-2522));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -2522
         //
         verifyException("statechart.SampleSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      // Undeclared exception!
      try { 
        sampleSimplified0.isStateActive((SampleSimplified.State) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("statechart.SampleSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.raiseTimeEvent(1);
      assertTrue(sampleSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle_brightness();
      assertTrue(sampleSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.raiseTimeEvent(1);
      assertTrue(sampleSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.triggerWithoutEvent();
      assertTrue(sampleSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.raiseToggle_brightness();
      sampleSimplified0.raiseToggle();
      assertTrue(sampleSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.raiseToggle_brightness();
      sampleSimplified0.raiseToggle_brightness();
      sampleSimplified0.exit();
      assertFalse(sampleSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.raiseToggle_brightness();
      sampleSimplified0.exit();
      assertFalse(sampleSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.raiseToggle_brightness();
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.raiseToggle_brightness();
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.raiseToggle_brightness();
      sampleSimplified0.exit();
      assertFalse(sampleSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      assertTrue(sampleSimplified0.isActive());
      
      sampleSimplified0.exit();
      assertFalse(sampleSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.SAMPLE_LIGHT_LIGHTS_ON_TIMER_TIMER_WORKING_TIMER_STATUS_COUNTING_DOWN;
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertTrue(sampleSimplified0.isActive());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.SAMPLE_LIGHT_LIGHTS_ON_TIMER_TIMER_WORKING;
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.SAMPLE_LIGHT_LIGHTS_ON_BRIGHTNESS_LEVEL_LOW;
      sampleSimplified0.raiseToggle();
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertTrue(sampleSimplified0.isActive());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.SAMPLE_LIGHT_LIGHTS_ON;
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertTrue(sampleSimplified0.isActive());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.raiseToggle();
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.SAMPLE_LIGHT_LIGHTS_ON;
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertTrue(sampleSimplified0.isActive());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.SAMPLE_LIGHT_LIGHTS__OFF;
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertTrue(sampleSimplified0.isActive());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.$NULLSTATE$;
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.SAMPLE_LIGHT_LIGHTS_ON_TIMER_TIMER_WORKING;
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.SAMPLE_LIGHT_LIGHTS_ON;
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.SAMPLE_LIGHT_LIGHTS_ON_TIMER_TIMER_WORKING_TIMER_STATUS_TRIGGER_OFF;
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.SAMPLE_LIGHT_LIGHTS_ON_TIMER_TIMER_WORKING_TIMER_STATUS_COUNTING_DOWN;
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.SAMPLE_LIGHT_LIGHTS_ON_BRIGHTNESS_LEVEL_MED;
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.SAMPLE_LIGHT_LIGHTS_ON_BRIGHTNESS_LEVEL_LOW;
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.SAMPLE_LIGHT_LIGHTS_ON_BRIGHTNESS_LEVEL_HIGH;
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      SampleSimplified.State sampleSimplified_State0 = SampleSimplified.State.SAMPLE_LIGHT_LIGHTS__OFF;
      boolean boolean0 = sampleSimplified0.isStateActive(sampleSimplified_State0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.raiseToggle();
      assertFalse(sampleSimplified0.isFinal());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      boolean boolean0 = sampleSimplified0.isActive();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      boolean boolean0 = sampleSimplified0.isActive();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      sampleSimplified0.exit();
      assertFalse(sampleSimplified0.isFinal());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      // Undeclared exception!
      try { 
        sampleSimplified0.enter();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Timer service must be set.
         //
         verifyException("statechart.SampleSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      // Undeclared exception!
      try { 
        sampleSimplified0.triggerWithoutEvent();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Timer service must be set.
         //
         verifyException("statechart.SampleSimplified", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      assertFalse(sampleSimplified0.isActive());
      
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.raiseTimeEvent(0);
      assertTrue(sampleSimplified0.isActive());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      boolean boolean0 = sampleSimplified0.isFinal();
      assertFalse(sampleSimplified0.isActive());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      SampleSimplified sampleSimplified0 = new SampleSimplified();
      ITimerService iTimerService0 = mock(ITimerService.class, new ViolatedAssumptionAnswer());
      sampleSimplified0.setTimerService(iTimerService0);
      sampleSimplified0.enter();
      sampleSimplified0.raiseToggle();
      sampleSimplified0.raiseToggle_brightness();
      sampleSimplified0.raiseToggle_brightness();
      sampleSimplified0.raiseToggle();
      assertTrue(sampleSimplified0.isActive());
  }
}
